increment4
tsupko/shortener pull request #3
Opened 2022-10-02 08:10 UTC by tsupko

2022-10-11 15:48 UTC, tmvrus requested changes

2022-10-11 15:48 UTC, tmvrus commented on cmd/shortener/main.go
> +	log.Fatalln(http.ListenAndServe(cfg.ServerAddress, router))
не очень хорошая практика так заворачивать ListenAndServe, даже если сервис остановится без ошибки, то все равно будет вызван Fatal что в свою очередь вернет ОС код завершения 1

2022-10-11 15:48 UTC, tmvrus commented on internal/app/api/handler.go
> +	}(r.Body)
нет большого смысла в том что бы передвать body как аргумент, вполне можно использовать r из родительской ф-и: это упростит код

2022-10-11 15:48 UTC, tmvrus commented on internal/app/api/handler.go
> +		fmt.Printf("Error while reading request body: %v\n", err)
вот тут надо бы завершить работу хенделера, поскольку тело запроса прочитать не удалось, то и выполнять ничего не надо

2022-10-11 15:48 UTC, tmvrus commented on internal/app/api/handler.go
> +		log.Fatal("can not unmarshal body:[", string(resBody), "] ", err)
тут лучше не использовать Fatal а вернуть ошибку клиенту, Fatal вызовет панику и клиент не узнает что он прислал невалидный JSON который не получилось анмаршалить, лучше тут вернуть BadRequest

2022-10-11 15:48 UTC, tmvrus commented on internal/app/api/handler.go
> +	}
вот тут тоже лучше вернуть ошибку клиенту явным образом

2022-10-11 15:48 UTC, tmvrus commented on internal/app/api/handler.go
> +		fmt.Printf("Error while writing response: %v\n", err)
для логирования лучше использовать пакет log

2022-10-11 15:48 UTC, tmvrus commented on internal/app/api/middleware.go
> +				return
тут хорошо бы ответить клиенту Internal Error

2022-10-11 15:48 UTC, tmvrus commented on internal/app/api/middleware.go
> +				fmt.Printf("Error while closing writer: %v\n", err)
fmt -> log

2022-10-11 15:48 UTC, tmvrus commented on internal/app/api/router.go
>  			_ = chi.URLParam(r, "id")
ценность вот этой сточки кода остается загадкой

2022-10-11 15:48 UTC, tmvrus commented on internal/app/storage/fileStorage.go
> +package storage
обычно используют underscore naming,то есть fileStorage.go -> file_storage.go

2022-10-11 15:48 UTC, tmvrus commented on internal/app/storage/fileStorage.go
> +		log.Fatal(err)
все таки лучше возвращать ошибку клиенту, иначе он может думать что все хорошо, а на самом деле запись в файл не прошла

2022-10-11 15:48 UTC, tmvrus commented on internal/app/storage/file.log
> +{"hash":"fklvHzLf","url":"url"}
обычно директорию с исходным кодом не используют для данных

2022-10-11 15:48 UTC, tmvrus commented on internal/app/storage/fileHandler.go
> +func NewProducer(filename string) (*Producer, error) {
Producer,Consumer,Record сделаны экспортируемыми но используются только в рамках этого пакета

2022-10-17 16:32 UTC, tmvrus requested changes

2022-10-17 16:32 UTC, tmvrus commented on internal/app/api/handler.go
> +		http.Error(w, "Could not unmarshal request: "+err.Error(), http.StatusBadRequest)
Хендлер продолжит работать после ошибки.

2022-10-17 16:32 UTC, tmvrus commented on internal/app/api/handler.go
> +}
эти два типа сделаны экспортируемыми, хотя используются только внутри своего пакета

2022-10-17 16:32 UTC, tmvrus commented on internal/app/api/handler.go
> +		http.Error(w, "Could not marshal response: "+err.Error(), http.StatusInternalServerError)
Хендлер продолжит работать после ошибки.

2022-10-17 16:32 UTC, tmvrus commented on internal/app/api/handler_test.go
> +					panic("unexpected path:" + tt.request.path)
есть хорошая альтернатива panic в тестах - `t.Fatalf`

2022-10-17 16:32 UTC, tmvrus commented on internal/app/api/middleware.go
> +			}
тут видимо должно быть что-то вроде 
```
http.Error(w, err.Error(), http.StatusInternalServerError)
return
```
как в gzipRequestHandle

2022-10-17 16:32 UTC, tmvrus commented on internal/app/storage/file_storage.go
> +	for i := 0; ; i++ {
есть краткая форма для такго рода циклов
```
for {
  // code here
}
```

2022-10-18 11:04 UTC, tsupko commented on internal/app/api/handler.go
> +		http.Error(w, "Could not unmarshal request: "+err.Error(), http.StatusBadRequest)
принято

2022-10-18 11:04 UTC, tsupko commented on internal/app/api/handler.go
> +}
принято

2022-10-18 11:04 UTC, tsupko commented on internal/app/api/handler.go
> +		http.Error(w, "Could not marshal response: "+err.Error(), http.StatusInternalServerError)
принято

2022-10-18 11:04 UTC, tsupko commented on internal/app/api/handler_test.go
> +					panic("unexpected path:" + tt.request.path)
принято

2022-10-18 11:04 UTC, tsupko commented on internal/app/api/middleware.go
> +			}
принято

2022-10-18 11:04 UTC, tsupko commented on internal/app/storage/file_storage.go
> +	for i := 0; ; i++ {
принято

2022-10-22 15:31 UTC, tsupko commented on internal/app/api/middleware.go
> +			}
здесь `err` во вложенной области видимости, поэтому если добавить `http.Error(w, err.Error(), http.StatusInternalServerError)` на строке 36, то возникнет ошибка `internal/app/api/middleware.go:36:27: nil dereference in dynamic method call`. Не исключено, что я не так понял замечание, но вроде понял, поэтому оставлю как есть

2022-10-25 13:13 UTC, tmvrus approved these changes
Очень хорошо

2022-10-25 13:13 UTC, tmvrus commented on internal/app/api/middleware.go
> +			}
видимо я не так выразился, 
вот этот код 
```
_, err := io.WriteString(w, err.Error())
```
лишний, нужно сразу отдавать InternalError

2022-10-25 17:11 UTC, merged